name: iapr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - albumentations=1.0.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - charls=2.2.0
  - cloudpickle=1.6.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.6.0
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.5.0
  - geos=3.9.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - icu=68.1
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - imgaug=0.4.0
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jbig=2.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lame=3.100
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libcxx=11.1.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.68.2
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libopencv=4.5.1
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=11.1.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - matplotlib-base=3.4.2
  - mkl=2021.2.0
  - nb_conda_kernels=2.3.1
  - ncurses=6.2
  - nettle=3.6
  - networkx=2.5
  - ninja=1.10.2
  - olefile=0.46
  - opencv=4.5.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - partd=1.2.0
  - pcre=8.44
  - pip=21.0.1
  - pixman=0.40.0
  - py-opencv=4.5.1
  - pyparsing=2.4.7
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.4.0
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - readline=8.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.34.0
  - tbb=2021.2.0
  - tk=8.6.10
  - toolz=0.11.1
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - tornado=6.1
  - traitlets=5.0.5
  - wheel=0.36.2
  - x264=1!161.3030
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - decorator==4.4.2
    - defusedxml==0.7.1
    - entrypoints==0.3
    - ipykernel==5.5.0
    - ipython==7.21.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-console==6.3.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numpy==1.20.1
    - opencv-python==4.5.1.48
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.2
    - plotly==4.14.3
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.17
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.8.1
    - pyrsistent==0.17.3
    - qtconsole==5.0.3
    - qtpy==1.9.0
    - retrying==1.3.3
    - scikit-image==0.18.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - send2trash==1.5.0
    - terminado==0.9.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2021.3.17
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
